version: "2.1"

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        environment:
            - DB_HOST=db
            - DB_NAME=tdum
            - DB_USER=root
            - DB_PASSWORD=root
        depends_on:
            - db

    db:
        image: mariadb:10.1
        restart: on-failure
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=tdum

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./apps/api:/usr/src/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        restart: on-failure
        depends_on:
            - php
