version: "2.1"

services:
    php:
        user: ${LOCAL_USER}
        volumes:
            - './apps/api:/usr/src/app'

    nginx:
        ports:
            - '${NGINX_PORT}:80'
        volumes:
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
